
excluded:
  - ProjectManager/AppDelegate.swift
  - ProjectManager/SceneDelegate.swift
  - ProjectManager/Presentation/ScheduleItem/View/ScheduleItemViewController.swift
  - ProjectManager/Data/DataSource/Network/Firestore/FirestoreService.swift
  - ProjectManager/Data/DataSource/Local/Realm/RealmService.swift

#function_body_length:
#    warning: 10
#    error: 15
type_body_length:
    warning: 200
    error: 250

disabled_rules:
  - identifier_name
